### ISSUE TITLE
Repeated question, wrong answer

### ISSUE THREAD

**Issue by michiexile** [mth229/mth229.github.io#17]
The question at:
https://github.com/mth229/mth229.github.io/blob/4e6a6a82384ee5ddf13079672febcfb82a626f2b/quarto/limits.qmd#L1256

And the question at: 
https://github.com/mth229/mth229.github.io/blob/4e6a6a82384ee5ddf13079672febcfb82a626f2b/quarto/limits.qmd#L1273

are identical.

Additionally,
```
@syms x
limit((x^x-1)/x, x => 0, dir="+")
```
yields
```
−∞
```
which is not an option among the offered answers.

**Comment by jverzani** [comment]
Dang, that's not good. I'll fix unless you get back to it first.

**Comment by michiexile** [comment]
It's an issue precisely because I couldn't see a good way to fix it directly.

--
Mikael Vejdemo-Johansson
***@***.*** ***@***.***>

**Comment by jverzani** [comment]
Yup, had to actually add the correct answer and replaced the other. Fixed with the next push to gh-pages
