### ISSUE TITLE
Answer does not agree with computations

### ISSUE THREAD

**Issue by michiexile** [mth229/mth229.github.io#18]
In the question at:
https://github.com/mth229/mth229.github.io/blob/4e6a6a82384ee5ddf13079672febcfb82a626f2b/quarto/derivatives.qmd#L383

We are instructed to examine `f(x) = exp(x)` and `fp(x) = Df(f, h=0.001)(x)` and graphically estimate their largest difference on [0,3].
The code prescribes the answer "approximately zero". However, when actually plotting out the difference, say with:
```
f(x) = exp(x)
fp(x) = Df(f, h=0.001)(x)
plot(x -> fp(x)-f(x), 0, 3)
```
we get something like this figure:

![newplot (1)](https://user-images.githubusercontent.com/32558/184444741-b7e873be-4c14-4d2c-961b-d658edd2166c.png)

From the figure, the answer suggests itself as .01 not 0.

**Comment by jverzani** [comment]
Hmm, that is a not-so-good question. I'm guessing -- but is has been awhile -- that I was expecting a plot of both functions, not the difference, which is bad form. I think I'll edit to be more prescriptive of how to assess this and adjust the answers. Thanks

**Comment by jverzani** [comment]
Nope, just typed in the wrong answer. Thanks. Fixed with next push to gh-pages.
