### ISSUE TITLE
Spelling error, sentence terminates weirdly

### ISSUE THREAD

**Issue by michiexile** [mth229/mth229.github.io#32]
https://github.com/mth229/mth229.github.io/blob/334ddd2edc07732986c4c1be7820766b6cfbc46c/quarto/integration.qmd#L525

`serveral` should be `several`. Also, the sentence terminates before telling us what it is that `Cubature` provides several of.

**Comment by jverzani** [comment]
Will fix once you have finished up with your edit cycle. Thanks!

**Comment by michiexile** [comment]
Done now.

--
Mikael Vejdemo-Johansson
***@***.*** ***@***.***>
