### ISSUE TITLE
Unreasonable answer

### ISSUE THREAD

**Issue by michiexile** [mth229/mth229.github.io#41]
https://github.com/mth229/mth229.github.io/blob/96938935be7700668f0cc0d3204fc9cc5bc9bbbf/quarto/integration.qmd#L1048

I refuse to believe that the reasonable answer to this question would be a cable length of 2 meters (6 feet). To span across the Verrazzano Narrows?
Should maybe the limits of integration be `-a, a`?

**Comment by jverzani** [comment]
Who you going to believe, the web page or your lying eyes? Can't get anything past you!

**Comment by jverzani** [comment]
Do you want me to adjust? Happy to do so, just let me know.

**Comment by michiexile** [comment]
I'll let you fix it.

--
Mikael Vejdemo-Johansson
***@***.*** ***@***.***>

**Comment by jverzani** [comment]
Thanks again!
