### ISSUE TITLE
Should this show an error?

### ISSUE THREAD

**Issue by michiexile** [mth229/mth229.github.io#44]
https://github.com/mth229/mth229.github.io/blob/78b9112c79e7aed1272129457c6bbcc91c8bbfa9/quarto/functions.qmd#L1246

The text talks about not being able to redefine one function type as another, but here we are just redefining an anonymous function to another anonymous function. Should this be instead

```
g1 = x -> sin(2x^2)
```

**Comment by jverzani** [comment]
Thanks, it definitely should. I'll put in a change.
