### ISSUE TITLE
Reword latest released version

### ISSUE THREAD

**Issue by trevorgunn** [mth229/mth229.github.io#60]
I don't know how useful it is to put a version number here (1.8) given that the latest number is always changing:

https://github.com/mth229/mth229.github.io/blob/1ab48d887bdcbfd42e438420a0b5a039223635b8/quarto/index.qmd#L116

I suggest changing the wording to just "latest stable release" or similar.

**Comment by mth229** [comment]
Thanks! I just put in a change.

BTW, if you have a github acct, feel free to click the edit page button and suggest changes that way. It is supposed to be pretty easy.
